# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jlamb/go/src/github.com/jlambatl/lua-blaze-jsonschema

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jlamb/go/src/github.com/jlambatl/lua-blaze-jsonschema

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"sourcemeta_blaze_dev\" \"sourcemeta_core_dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jlamb/go/src/github.com/jlambatl/lua-blaze-jsonschema/CMakeFiles /Users/jlamb/go/src/github.com/jlambatl/lua-blaze-jsonschema//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jlamb/go/src/github.com/jlambatl/lua-blaze-jsonschema/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named blaze

# Build rule for target.
blaze: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blaze
.PHONY : blaze

# fast build rule for target.
blaze/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blaze.dir/build.make CMakeFiles/blaze.dir/build
.PHONY : blaze/fast

#=============================================================================
# Target rules for targets named mpdecimal

# Build rule for target.
mpdecimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mpdecimal
.PHONY : mpdecimal

# fast build rule for target.
mpdecimal/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/CMakeFiles/mpdecimal.dir/build.make deps/blaze/vendor/core/CMakeFiles/mpdecimal.dir/build
.PHONY : mpdecimal/fast

#=============================================================================
# Target rules for targets named sljit

# Build rule for target.
sljit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sljit
.PHONY : sljit

# fast build rule for target.
sljit/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/CMakeFiles/sljit.dir/build.make deps/blaze/vendor/core/CMakeFiles/sljit.dir/build
.PHONY : sljit/fast

#=============================================================================
# Target rules for targets named pcre2

# Build rule for target.
pcre2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pcre2
.PHONY : pcre2

# fast build rule for target.
pcre2/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/CMakeFiles/pcre2.dir/build.make deps/blaze/vendor/core/CMakeFiles/pcre2.dir/build
.PHONY : pcre2/fast

#=============================================================================
# Target rules for targets named yaml

# Build rule for target.
yaml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml
.PHONY : yaml

# fast build rule for target.
yaml/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/CMakeFiles/yaml.dir/build.make deps/blaze/vendor/core/CMakeFiles/yaml.dir/build
.PHONY : yaml/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_io

# Build rule for target.
sourcemeta_core_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_io
.PHONY : sourcemeta_core_io

# fast build rule for target.
sourcemeta_core_io/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/lang/io/CMakeFiles/sourcemeta_core_io.dir/build.make deps/blaze/vendor/core/src/lang/io/CMakeFiles/sourcemeta_core_io.dir/build
.PHONY : sourcemeta_core_io/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_process

# Build rule for target.
sourcemeta_core_process: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_process
.PHONY : sourcemeta_core_process

# fast build rule for target.
sourcemeta_core_process/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/lang/process/CMakeFiles/sourcemeta_core_process.dir/build.make deps/blaze/vendor/core/src/lang/process/CMakeFiles/sourcemeta_core_process.dir/build
.PHONY : sourcemeta_core_process/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_parallel

# Build rule for target.
sourcemeta_core_parallel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_parallel
.PHONY : sourcemeta_core_parallel

# fast build rule for target.
sourcemeta_core_parallel/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/lang/parallel/CMakeFiles/sourcemeta_core_parallel.dir/build.make deps/blaze/vendor/core/src/lang/parallel/CMakeFiles/sourcemeta_core_parallel.dir/build
.PHONY : sourcemeta_core_parallel/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_numeric

# Build rule for target.
sourcemeta_core_numeric: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_numeric
.PHONY : sourcemeta_core_numeric

# fast build rule for target.
sourcemeta_core_numeric/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/lang/numeric/CMakeFiles/sourcemeta_core_numeric.dir/build.make deps/blaze/vendor/core/src/lang/numeric/CMakeFiles/sourcemeta_core_numeric.dir/build
.PHONY : sourcemeta_core_numeric/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_punycode

# Build rule for target.
sourcemeta_core_punycode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_punycode
.PHONY : sourcemeta_core_punycode

# fast build rule for target.
sourcemeta_core_punycode/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/core/punycode/CMakeFiles/sourcemeta_core_punycode.dir/build.make deps/blaze/vendor/core/src/core/punycode/CMakeFiles/sourcemeta_core_punycode.dir/build
.PHONY : sourcemeta_core_punycode/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_regex

# Build rule for target.
sourcemeta_core_regex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_regex
.PHONY : sourcemeta_core_regex

# fast build rule for target.
sourcemeta_core_regex/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/core/regex/CMakeFiles/sourcemeta_core_regex.dir/build.make deps/blaze/vendor/core/src/core/regex/CMakeFiles/sourcemeta_core_regex.dir/build
.PHONY : sourcemeta_core_regex/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_uri

# Build rule for target.
sourcemeta_core_uri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_uri
.PHONY : sourcemeta_core_uri

# fast build rule for target.
sourcemeta_core_uri/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/core/uri/CMakeFiles/sourcemeta_core_uri.dir/build.make deps/blaze/vendor/core/src/core/uri/CMakeFiles/sourcemeta_core_uri.dir/build
.PHONY : sourcemeta_core_uri/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_json

# Build rule for target.
sourcemeta_core_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_json
.PHONY : sourcemeta_core_json

# fast build rule for target.
sourcemeta_core_json/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/core/json/CMakeFiles/sourcemeta_core_json.dir/build.make deps/blaze/vendor/core/src/core/json/CMakeFiles/sourcemeta_core_json.dir/build
.PHONY : sourcemeta_core_json/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_jsonpointer

# Build rule for target.
sourcemeta_core_jsonpointer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_jsonpointer
.PHONY : sourcemeta_core_jsonpointer

# fast build rule for target.
sourcemeta_core_jsonpointer/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/core/jsonpointer/CMakeFiles/sourcemeta_core_jsonpointer.dir/build.make deps/blaze/vendor/core/src/core/jsonpointer/CMakeFiles/sourcemeta_core_jsonpointer.dir/build
.PHONY : sourcemeta_core_jsonpointer/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_jsonschema

# Build rule for target.
sourcemeta_core_jsonschema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_jsonschema
.PHONY : sourcemeta_core_jsonschema

# fast build rule for target.
sourcemeta_core_jsonschema/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/core/jsonschema/CMakeFiles/sourcemeta_core_jsonschema.dir/build.make deps/blaze/vendor/core/src/core/jsonschema/CMakeFiles/sourcemeta_core_jsonschema.dir/build
.PHONY : sourcemeta_core_jsonschema/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_jsonl

# Build rule for target.
sourcemeta_core_jsonl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_jsonl
.PHONY : sourcemeta_core_jsonl

# fast build rule for target.
sourcemeta_core_jsonl/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/core/jsonl/CMakeFiles/sourcemeta_core_jsonl.dir/build.make deps/blaze/vendor/core/src/core/jsonl/CMakeFiles/sourcemeta_core_jsonl.dir/build
.PHONY : sourcemeta_core_jsonl/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_yaml

# Build rule for target.
sourcemeta_core_yaml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_yaml
.PHONY : sourcemeta_core_yaml

# fast build rule for target.
sourcemeta_core_yaml/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/core/yaml/CMakeFiles/sourcemeta_core_yaml.dir/build.make deps/blaze/vendor/core/src/core/yaml/CMakeFiles/sourcemeta_core_yaml.dir/build
.PHONY : sourcemeta_core_yaml/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_alterschema

# Build rule for target.
sourcemeta_core_alterschema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_alterschema
.PHONY : sourcemeta_core_alterschema

# fast build rule for target.
sourcemeta_core_alterschema/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/extension/alterschema/CMakeFiles/sourcemeta_core_alterschema.dir/build.make deps/blaze/vendor/core/src/extension/alterschema/CMakeFiles/sourcemeta_core_alterschema.dir/build
.PHONY : sourcemeta_core_alterschema/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_editorschema

# Build rule for target.
sourcemeta_core_editorschema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_editorschema
.PHONY : sourcemeta_core_editorschema

# fast build rule for target.
sourcemeta_core_editorschema/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/extension/editorschema/CMakeFiles/sourcemeta_core_editorschema.dir/build.make deps/blaze/vendor/core/src/extension/editorschema/CMakeFiles/sourcemeta_core_editorschema.dir/build
.PHONY : sourcemeta_core_editorschema/fast

#=============================================================================
# Target rules for targets named sourcemeta_core_schemaconfig

# Build rule for target.
sourcemeta_core_schemaconfig: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_core_schemaconfig
.PHONY : sourcemeta_core_schemaconfig

# fast build rule for target.
sourcemeta_core_schemaconfig/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/vendor/core/src/extension/schemaconfig/CMakeFiles/sourcemeta_core_schemaconfig.dir/build.make deps/blaze/vendor/core/src/extension/schemaconfig/CMakeFiles/sourcemeta_core_schemaconfig.dir/build
.PHONY : sourcemeta_core_schemaconfig/fast

#=============================================================================
# Target rules for targets named sourcemeta_blaze_compiler

# Build rule for target.
sourcemeta_blaze_compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_blaze_compiler
.PHONY : sourcemeta_blaze_compiler

# fast build rule for target.
sourcemeta_blaze_compiler/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/src/compiler/CMakeFiles/sourcemeta_blaze_compiler.dir/build.make deps/blaze/src/compiler/CMakeFiles/sourcemeta_blaze_compiler.dir/build
.PHONY : sourcemeta_blaze_compiler/fast

#=============================================================================
# Target rules for targets named sourcemeta_blaze_evaluator

# Build rule for target.
sourcemeta_blaze_evaluator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_blaze_evaluator
.PHONY : sourcemeta_blaze_evaluator

# fast build rule for target.
sourcemeta_blaze_evaluator/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/src/evaluator/CMakeFiles/sourcemeta_blaze_evaluator.dir/build.make deps/blaze/src/evaluator/CMakeFiles/sourcemeta_blaze_evaluator.dir/build
.PHONY : sourcemeta_blaze_evaluator/fast

#=============================================================================
# Target rules for targets named sourcemeta_blaze_output

# Build rule for target.
sourcemeta_blaze_output: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_blaze_output
.PHONY : sourcemeta_blaze_output

# fast build rule for target.
sourcemeta_blaze_output/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/src/output/CMakeFiles/sourcemeta_blaze_output.dir/build.make deps/blaze/src/output/CMakeFiles/sourcemeta_blaze_output.dir/build
.PHONY : sourcemeta_blaze_output/fast

#=============================================================================
# Target rules for targets named sourcemeta_blaze_linter

# Build rule for target.
sourcemeta_blaze_linter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_blaze_linter
.PHONY : sourcemeta_blaze_linter

# fast build rule for target.
sourcemeta_blaze_linter/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/src/linter/CMakeFiles/sourcemeta_blaze_linter.dir/build.make deps/blaze/src/linter/CMakeFiles/sourcemeta_blaze_linter.dir/build
.PHONY : sourcemeta_blaze_linter/fast

#=============================================================================
# Target rules for targets named sourcemeta_blaze_test

# Build rule for target.
sourcemeta_blaze_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_blaze_test
.PHONY : sourcemeta_blaze_test

# fast build rule for target.
sourcemeta_blaze_test/fast:
	$(MAKE) $(MAKESILENT) -f deps/blaze/src/test/CMakeFiles/sourcemeta_blaze_test.dir/build.make deps/blaze/src/test/CMakeFiles/sourcemeta_blaze_test.dir/build
.PHONY : sourcemeta_blaze_test/fast

src/luablaze.o: src/luablaze.cpp.o
.PHONY : src/luablaze.o

# target to build an object file
src/luablaze.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blaze.dir/build.make CMakeFiles/blaze.dir/src/luablaze.cpp.o
.PHONY : src/luablaze.cpp.o

src/luablaze.i: src/luablaze.cpp.i
.PHONY : src/luablaze.i

# target to preprocess a source file
src/luablaze.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blaze.dir/build.make CMakeFiles/blaze.dir/src/luablaze.cpp.i
.PHONY : src/luablaze.cpp.i

src/luablaze.s: src/luablaze.cpp.s
.PHONY : src/luablaze.s

# target to generate assembly for a file
src/luablaze.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blaze.dir/build.make CMakeFiles/blaze.dir/src/luablaze.cpp.s
.PHONY : src/luablaze.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... blaze"
	@echo "... mpdecimal"
	@echo "... pcre2"
	@echo "... sljit"
	@echo "... sourcemeta_blaze_compiler"
	@echo "... sourcemeta_blaze_evaluator"
	@echo "... sourcemeta_blaze_linter"
	@echo "... sourcemeta_blaze_output"
	@echo "... sourcemeta_blaze_test"
	@echo "... sourcemeta_core_alterschema"
	@echo "... sourcemeta_core_editorschema"
	@echo "... sourcemeta_core_io"
	@echo "... sourcemeta_core_json"
	@echo "... sourcemeta_core_jsonl"
	@echo "... sourcemeta_core_jsonpointer"
	@echo "... sourcemeta_core_jsonschema"
	@echo "... sourcemeta_core_numeric"
	@echo "... sourcemeta_core_parallel"
	@echo "... sourcemeta_core_process"
	@echo "... sourcemeta_core_punycode"
	@echo "... sourcemeta_core_regex"
	@echo "... sourcemeta_core_schemaconfig"
	@echo "... sourcemeta_core_uri"
	@echo "... sourcemeta_core_yaml"
	@echo "... yaml"
	@echo "... src/luablaze.o"
	@echo "... src/luablaze.i"
	@echo "... src/luablaze.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

